---
title: Changbal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Publication
email: changbalpub@gmail.com
description: 한국에서 미국 테크 업계로 취업하자!
baseurl: ''
url: ''
author: 
street_address: 1234 Somewhere Road
city: HH CITY22
state: B State
zip_code: 55555
country: GHSNF Country2222
phone: "(222) 555-5555"
tiles-source: posts
tiles-count: 8
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 
markdown: kramdown
sass:
  style: compressed
